"""Share by lens: four separately labelled measurements that are never added together.

PLAN §3 M3, EXECUTION W2c, section H "Share rules" of docs/EVALUATION_PLAN.md. "Share" in payments depends
entirely on what is counted, so this module never produces one market-share number. It produces four lenses,
each with its own denominator, unit and caveats, in one long table, plus a concentration (HHI) table for the
lenses where a closed pool exists:

``disclosed_pool``         each listed company's payment volume as a share of the sum over the companies in the
                           same layer that disclose a comparable volume for the same calendar period. Labelled
                           "share of disclosed pool", never market share. HHI is computed inside the pool only.
``official_denominator``   a company's volume over an official total, only when scope (US vs global), measure
                           and period match. BNPL uses the Fed FEDS Note table, whose numerators and total come
                           from the same table. Every mismatch is a *refusal row*: no number, a reason instead.
``web_coverage``           HTTP Archive origins carrying a technology, over all origins in the crawl slice
                           (webtech.py output). Always "coverage", never share of payments.
``developer_downloads``    share of npm downloads among the pinned SDK set (devstats.py output). Downloads are
                           not developers and not dollars.

Rules this module enforces (each has a test)
--------------------------------------------
* **Chartable rows only.** A curated row reaches a number in this table only when ``chartable`` is true (tag V or
  C; ``reported_talks`` / ``third_party_estimate`` are never chartable, reference.py guarantees it). A pool member
  whose row is not chartable appears as an ``excluded`` row with the reason and no value. Private rows that are
  not chartable are dropped entirely: they belong in the separate "reported, unconfirmed" table (ledger.py).
* **Layers are never summed.** A pool belongs to one layer; the HHI table has one row per (lens, pool, period)
  and a pool total is the sum of that pool's members only. Lenses are never combined: web coverage overlaps
  (one origin carries several technologies) and downloads are not volume.
* **One period, one definition.** Fiscal periods are aligned to calendar periods by their end date
  (``calendar_period``); a fiscal quarter that does not end in March/June/September/December is refused, not
  shifted. Annualised run rates (``stated_run_rate`` rows) never enter a pool of period totals. Half-year figures
  enter only a calendar-year pool, and only as H1 + H2.
* **One currency.** Pools are in USD. share.py does not convert currencies: a converted volume would carry an
  exchange-rate choice into every other member's share. A member reporting in EUR or AUD is excluded with that
  reason (Adyen, Zip), so the exclusion is visible on the page instead of buried in a rate.
* **Private companies are markers, never pool members.** Decision for Stripe (and Checkout.com, Ramp, Mercury,
  Airwallex): a stated private volume is shown beside the pool as a ``marker`` row with its own qualifier, and
  never enters the pool sum, even where the period matches. Three reasons: (1) it is a company statement, not a
  filing, and its definition is not broken down ("total volume generated by businesses running on Stripe");
  (2) private figures are annual or annualised, while pools are mostly quarterly; (3) it overlaps public pool
  members: Shopify Payments is processed by Stripe, so Stripe's total already contains Shopify's gross payments
  volume, and adding both would count the same dollar twice. Q1 is the exception the registration itself makes:
  it needs Stripe's share of a named five-company set, which ``q1_volume_share`` computes as an interval.

Qualifier propagation (``=`` exact, ``>`` lower bound, ``<`` upper bound, ``~`` approximate)
---------------------------------------------------------------------------------------------
``q_sum``    a sum of exact values is exact; ``~`` anywhere makes it ``~``; ``=`` with ``>`` is ``>`` (a lower
             bound plus exact values is a lower bound); ``=`` with ``<`` is ``<``; ``>`` with ``<`` is ``~``: the
             two bounds point in opposite directions, so the result is neither bound. It is not refused, because
             the point value is still the best reading, but it is never presented as a bound.
``q_ratio``  numerator / denominator, positive values: the denominator's direction flips (a lower-bound
             denominator gives an upper-bound ratio), then the two combine as in ``q_sum``.
``q_share``  x / (x + rest) rises with x and falls with rest, so it is ``q_ratio`` of x against the rest:
             a member with ``>`` volume gets a ``>`` share, and every other member a ``<`` share.
``q_hhi``    a sum of squared shares moves in both directions when one input is a bound, so any non-exact share
             makes the HHI ``~``.

Usage::

    uv run python -m pipelines.payments.share            # build and write data/marts/payments/share_*.parquet
    uv run python -m pipelines.payments.share --dry-run  # build, validate, print checks, write nothing
"""

from __future__ import annotations

import argparse
import logging
import math
import re
import sys
from collections.abc import Iterable
from dataclasses import dataclass, field
from datetime import date
from pathlib import Path

import pandera.polars as pa
import polars as pl

from pipelines.common.checks import check, uniqueness
from pipelines.common.log import setup_logging
from pipelines.common.storage import MARTS_DIR, write_parquet
from pipelines.payments import reference
from pipelines.payments.config import NEVER_CHARTED_KINDS, NPM_CLIENT_SDKS, NPM_SERVER_SDKS, UNIVERSE

log = logging.getLogger("payments.share")

OUT_DIR = MARTS_DIR / "payments"
LONG_FILE = "share_lenses.parquet"
HHI_FILE = "share_pool_hhi.parquet"

LENSES = ["disclosed_pool", "official_denominator", "web_coverage", "developer_downloads"]
ROLES = ["member", "marker", "excluded", "refused", "measured"]
QUALIFIERS = ["=", ">", "<", "~"]

UNIT_POOL = "share_of_disclosed_pool"
UNIT_OFFICIAL = "share_of_official_total"
UNIT_ORIGINS = "share_of_origins"
UNIT_DOWNLOADS = "share_of_downloads"
SHARE_UNITS = [UNIT_POOL, UNIT_OFFICIAL, UNIT_ORIGINS, UNIT_DOWNLOADS]
USD = "USD"

#: Used only to turn a ``~`` figure into an interval (``q1_volume_share``). Curated ``~`` rows are rounded
#: company figures (Shift4 to whole billions), so 5% comfortably covers the rounding.
APPROX_REL_TOL = 0.05

#: A pool share needs at least two members; one member is 100% by construction.
MIN_POOL_MEMBERS = 2

# --- qualifier algebra -----------------------------------------------------------------------


def flip(q: str) -> str:
    """Direction of a quantity that enters with a negative sign (a denominator, the rest of a pool)."""
    return {">": "<", "<": ">"}.get(q, q)


def q_sum(qs: Iterable[str]) -> str:
    s = set(qs)
    bad = s - set(QUALIFIERS)
    if bad:
        raise ValueError(f"unknown qualifier(s) {sorted(bad)}")
    if "~" in s or {">", "<"} <= s:
        return "~"
    if ">" in s:
        return ">"
    if "<" in s:
        return "<"
    return "="


def q_ratio(q_num: str, q_den: str) -> str:
    return q_sum([q_num, flip(q_den)])


def q_share(q_self: str, q_rest: str) -> str:
    return q_ratio(q_self, q_rest)


def q_hhi(share_qs: Iterable[str]) -> str:
    qs = list(share_qs)
    return "=" if all(q == "=" for q in qs) else "~"


def bounds(value: float, q: str) -> tuple[float, float]:
    """The interval a qualified figure stands for."""
    if q == "=":
        return value, value
    if q == ">":
        return value, math.inf
    if q == "<":
        return 0.0, value
    if q == "~":
        return value * (1 - APPROX_REL_TOL), value * (1 + APPROX_REL_TOL)
    raise ValueError(f"unknown qualifier {q!r}")


# --- calendar alignment ----------------------------------------------------------------------

_MONTH = ["", "January", "February", "March", "April", "May", "June", "July", "August", "September",
          "October", "November", "December"]


def granularity(period: str) -> str:
    if re.search(r"Q[1-4]$", period):
        return "quarter"
    if re.search(r"(^H[12]-\d{4}$)|(-H[12]$)", period):
        return "half"
    if re.fullmatch(r"FY\d{4}", period):
        return "year"
    return "other"  # a month ('2026-03') or a bare year label: point-in-time or run-rate statements


def calendar_period(period: str, as_of_date: str) -> tuple[str | None, str | None]:
    """(calendar label, refusal reason). The curated ``as_of_date`` is the period end, so a fiscal period is
    placed by where it ends: Affirm FY2026-Q4 (ends 2026-06-30) is 2026-Q2; Navan FY2027-Q2 (ends July) is no
    calendar quarter and is refused rather than shifted by a month."""
    g = granularity(period)
    end = date.fromisoformat(as_of_date[:10])
    if g == "quarter":
        if end.month % 3:
            return None, f"fiscal quarter ends in {_MONTH[end.month]}, not a calendar quarter"
        return f"{end.year}-Q{end.month // 3}", None
    if g == "half":
        if end.month not in (6, 12):
            return None, f"fiscal half ends in {_MONTH[end.month]}, not a calendar half"
        return f"H{end.month // 6}-{end.year}", None
    if g == "year":
        if end.month != 12:
            return None, f"fiscal year ends in {_MONTH[end.month]}, not a calendar year"
        return f"FY{end.year}", None
    return None, "not a period total (point-in-time or annualised statement)"


def period_sort_key(label: str | None) -> tuple[int, int]:
    """Calendar order; a year sorts after its fourth quarter."""
    if not label:
        return (0, 0)
    m = re.fullmatch(r"(\d{4})-Q([1-4])", label)
    if m:
        return int(m.group(1)), int(m.group(2)) * 2
    m = re.fullmatch(r"FY(\d{4})", label)
    if m:
        return int(m.group(1)), 9
    m = re.fullmatch(r"H([12])-(\d{4})", label)
    if m:
        return int(m.group(2)), int(m.group(1)) * 4 + 1
    return (0, 0)


# --- pinned pools ----------------------------------------------------------------------------


@dataclass(frozen=True)
class Member:
    company: str   # name as written in the curated KPI file
    metric: str    # metric as written in the curated KPI file
    label: str     # roster name (config.UNIVERSE)
    scope: str     # geography the volume covers
    measure: str   # what is counted, used to test like-for-like against an official denominator


@dataclass(frozen=True)
class Marker:
    company: str
    metric: str
    reason: str


@dataclass(frozen=True)
class Pool:
    id: str
    segment: str
    label: str
    basis: str
    members: tuple[Member, ...]
    markers: tuple[Marker, ...] = ()
    not_in_pool: dict[str, str] = field(default_factory=dict)  # roster company -> why it has no member row


_STRIPE_MARKER = ("private: a stated, unaudited calendar-year total with no line-level definition, annual only, "
                  "and it overlaps pool members (Shopify Payments is processed by Stripe), so adding it would "
                  "count the same dollar twice; shown beside the pool, never inside its sum")

POOLS: tuple[Pool, ...] = (
    Pool(
        id="A_payment_volume", segment="A", label="Merchant acceptance: payment volume",
        basis=("each company's own payment-volume definition (TPV, GPV, processed volume), calendar period, USD; "
               "definitions differ: PayPal TPV includes Venmo and P2P, Square GPV includes bank payments"),
        members=(
            Member("PayPal", "tpv", "PayPal", "global", "payment volume"),
            Member("Block", "square_gpv", "Block/Square", "global", "payment volume"),
            Member("Shopify", "gross_payments_volume", "Shopify Payments", "global", "payment volume"),
            Member("Toast", "gpv", "Toast", "US and international", "payment volume"),
            Member("Shift4", "volume", "Shift4", "global", "payment volume"),
            Member("Adyen", "processed_volume", "Adyen", "global", "payment volume"),
            Member("Fiserv", "clover_gpv_annualized", "Fiserv Clover", "US and international", "payment volume"),
        ),
        markers=(
            Marker("Stripe", "total_volume", _STRIPE_MARKER),
            Marker("Checkout.com", "total_payment_volume",
                   "private: a stated lower bound ('over $300B'), annual only; never inside the pool sum"),
        ),
        not_in_pool={"Global Payments": "no payment-volume row in the curated KPI file (revenue only)"},
    ),
    Pool(
        id="B_bnpl_gmv", segment="B", label="BNPL: gross merchandise volume",
        basis=("each company's GMV/TTV as defined by it, calendar period, USD; geography differs by member "
               "(Klarna global, Affirm US + Canada + UK, Sezzle US + Canada)"),
        members=(
            Member("Affirm", "GMV", "Affirm", "US + Canada + UK", "BNPL GMV"),
            Member("Klarna", "GMV", "Klarna", "global", "BNPL GMV"),
            Member("Sezzle", "GMV", "Sezzle", "US + Canada", "BNPL GMV"),
            Member("Zip", "TTV", "Zip", "ANZ + US", "BNPL GMV"),
        ),
        not_in_pool={
            "Afterpay": "no Afterpay volume row in the curated KPI files (it sits inside Block's Cash App); "
                        "measured in the official-denominator lens (Fed FEDS table)",
            "PayPal Pay Later": "no Pay Later volume row in the curated KPI files; measured in the "
                                "official-denominator lens (Fed FEDS table)",
        },
    ),
    Pool(
        id="C_b2b_payment_volume", segment="C", label="Corporate payments: B2B payment volume",
        basis="BILL total payment volume and Corpay Corporate Payments spend volume, calendar period, USD",
        members=(
            Member("BILL", "Total payment volume", "BILL", "US-focused", "B2B payment volume"),
            Member("Corpay", "Corporate Payments spend volume", "Corpay", "global", "B2B payment volume"),
        ),
        markers=(
            Marker("Ramp", "annualized_purchase_volume",
                   "private: an annualised run rate, never mixed with period totals"),
            Marker("Mercury", "transaction_volume",
                   "private: stated banking transaction volume, a different measure, annual only"),
        ),
        not_in_pool={
            "Navan": "gross booking volume counts travel bookings, not payments, and its fiscal quarters end in "
                     "January, April, July and October",
            "Brex": "no stated volume; part of Capital One since 2026-04-07 (Q6 bounds its spend by inference)",
            "Ramp": "private: shown as a marker", "Mercury": "private: shown as a marker",
        },
    ),
    Pool(
        id="D_crossborder_volume", segment="D", label="Cross-border: payment volume",
        basis=("Wise cross-border volume, Payoneer volume, dLocal TPV, Flywire TPV, calendar period, USD; "
               "dLocal includes local-to-local flows, Wise counts cross-border only"),
        members=(
            Member("Wise", "Cross-border volume", "Wise", "global", "cross-border payment volume"),
            Member("Payoneer", "Volume", "Payoneer", "global", "cross-border payment volume"),
            Member("dLocal", "TPV", "dLocal", "global", "cross-border payment volume"),
            Member("Flywire", "Total payment volume", "Flywire", "global", "cross-border payment volume"),
        ),
        markers=(
            Marker("Airwallex", "annualized_transaction_volume",
                   "private: an annualised run rate across products, never mixed with period totals"),
        ),
        not_in_pool={"Airwallex": "private: shown as a marker"},
    ),
    Pool(
        id="E_processing_volume", segment="E", label="Issuing infrastructure: processing volume",
        basis="Marqeta total processing volume; the other issuers are classification-table only",
        members=(Member("Marqeta", "Total processing volume", "Marqeta", "US and international",
                        "issuing processing volume"),),
    ),
)

#: Segments with no pool at all, and why.
NO_POOL = {"F": "stablecoin rails are a control layer, registered as never in share"}


@dataclass(frozen=True)
class Denominator:
    series: str
    metric: str
    segment: str
    scope: str
    measure: str
    label: str


#: Official totals a company volume could be divided by. Census NSA, not SA: company volumes are not
#: seasonally adjusted, so a quarter's actual sales is the like-for-like total.
DENOMINATORS: tuple[Denominator, ...] = (
    Denominator("census_ecomm_nsa", "us_retail_ecommerce_sales", "A", "US", "US retail e-commerce sales",
                "Census quarterly US retail e-commerce sales, not seasonally adjusted"),
    Denominator("fed_payments_study_2025", "us_card_payments_value", "A", "US", "US card payments value",
                "Federal Reserve Payments Study, value of US card payments"),
    Denominator("fed_feds_note_bnpl_2026", "us_bnpl_issuance_total", "B", "US", "BNPL credit issuance",
                "Fed FEDS Note table 2, US BNPL credit issuance, six providers"),
)

#: Segments with no official denominator, and why (registered default 5 for corporate cards).
NO_DENOMINATOR = {
    "C": "no market-wide denominator for commercial cards or B2B payments (registered default: pool ranking only)",
    "D": "no official cross-border volume denominator; the FSB publishes cost KPIs in percent, not volumes",
    "E": "no official denominator for issuing processing volume",
    "F": "stablecoin rails are a control layer, registered as never in share",
}

FEDS_SERIES = "fed_feds_note_bnpl_2026"
FEDS_TOTAL = "us_bnpl_issuance_total"
FEDS_COMPANY = {"affirm": "Affirm", "afterpay_block": "Afterpay", "klarna": "Klarna", "paypal": "PayPal Pay Later",
                "sezzle": "Sezzle", "zip": "Zip"}
FEDS_BASIS = ("Fed FEDS Note table 2: estimated 2025 US BNPL credit issuance by provider over the six-provider "
              "total; six firms, not the whole market; issuance, not GMV; US shares partly scaled from global "
              "figures by Fed staff")
#: Figure 1b prints whole-percent shares and table 2 prints $ billions to one decimal, so a share recomputed
#: from the table may sit up to half a percentage point (plus the table's own rounding) from the printed one.
FEDS_ROUNDING_PP = 0.5
FEDS_TABLE_HALF_UNIT = 0.05e9

#: HTTP Archive technology -> (layer, roster company). Wallet buttons (Apple/Google/Amazon Pay) are not roster
#: companies and overlap every processor, so they are left out of this lens.
WEB_TECH_COMPANY: dict[str, tuple[str, str]] = {
    "Stripe": ("A", "Stripe"), "PayPal": ("A", "PayPal"), "Braintree": ("A", "PayPal (Braintree)"),
    "Adyen": ("A", "Adyen"), "Square": ("A", "Block/Square"), "Shop Pay": ("A", "Shopify Payments"),
    "Checkout.com": ("A", "Checkout.com"), "Klarna Checkout": ("B", "Klarna"), "Afterpay": ("B", "Afterpay"),
    "Affirm": ("B", "Affirm"),
}

SEGMENT_OF: dict[str, str] = {c: seg for seg, d in UNIVERSE.items() for c in d["core"] + d["table"]}

# --- output schemas --------------------------------------------------------------------------

LONG_DTYPES: dict[str, pl.DataType] = {
    "segment": pl.Utf8,
    "lens": pl.Utf8,
    "pool": pl.Utf8,          # pool id, denominator series, or crawl / package slice
    "company": pl.Utf8,       # null on a segment-level refusal
    "period": pl.Utf8,        # calendar label; null on a pool-level exclusion
    "value": pl.Float64,      # null whenever refusal_reason is set
    "unit": pl.Utf8,
    "qualifier": pl.Utf8,     # null when value is null
    "role": pl.Utf8,
    "basis": pl.Utf8,
    "refusal_reason": pl.Utf8,
    "source_metric": pl.Utf8,
    "stale": pl.Boolean,
}
LONG_KEY = ["lens", "pool", "company", "period", "role", "source_metric"]

HHI_DTYPES: dict[str, pl.DataType] = {
    "segment": pl.Utf8,
    "lens": pl.Utf8,
    "pool": pl.Utf8,
    "period": pl.Utf8,
    "n_members": pl.Int64,
    "full_membership": pl.Boolean,  # n_members equals the pool's largest membership in any period
    "members": pl.Utf8,       # comma-separated roster names
    "excluded": pl.Utf8,      # "name (reason)" joined by "; "
    "pool_total": pl.Float64,
    "unit": pl.Utf8,
    "total_qualifier": pl.Utf8,
    "hhi": pl.Float64,        # 0-10,000 scale; null when refused
    "qualifier": pl.Utf8,
    "basis": pl.Utf8,
    "refusal_reason": pl.Utf8,
}
HHI_KEY = ["lens", "pool", "period"]


def _value_xor_reason(data) -> pl.LazyFrame:
    return data.lazyframe.select(pl.col("value").is_null() == pl.col("refusal_reason").is_not_null())


def _qualifier_with_value(data) -> pl.LazyFrame:
    return data.lazyframe.select(pl.col("value").is_null() == pl.col("qualifier").is_null())


def _share_in_unit_range(data) -> pl.LazyFrame:
    is_share = pl.col("unit").is_in(SHARE_UNITS)
    return data.lazyframe.select(~is_share | pl.col("value").is_null()
                                 | ((pl.col("value") >= 0) & (pl.col("value") <= 1)))


def _numbers_only_for_members(data) -> pl.LazyFrame:
    return data.lazyframe.select(~pl.col("role").is_in(["excluded", "refused"]) | pl.col("value").is_null())


LONG_SCHEMA = pa.DataFrameSchema(
    {
        "segment": pa.Column(str, pa.Check.isin(list(UNIVERSE))),
        "lens": pa.Column(str, pa.Check.isin(LENSES)),
        "pool": pa.Column(str),
        "company": pa.Column(str, nullable=True),
        "period": pa.Column(str, nullable=True),
        "value": pa.Column(float, pa.Check.ge(0.0), nullable=True),
        "unit": pa.Column(str),
        "qualifier": pa.Column(str, pa.Check.isin(QUALIFIERS), nullable=True),
        "role": pa.Column(str, pa.Check.isin(ROLES)),
        "basis": pa.Column(str),
        "refusal_reason": pa.Column(str, nullable=True),
        "source_metric": pa.Column(str, nullable=True),
        "stale": pa.Column(bool),
    },
    strict=True,
    coerce=False,
    checks=[
        pa.Check(_value_xor_reason, error="a row carries a value or a refusal reason, never both or neither"),
        pa.Check(_qualifier_with_value, error="qualifier must be present exactly when value is"),
        pa.Check(_share_in_unit_range, error="share outside [0, 1]"),
        pa.Check(_numbers_only_for_members, error="excluded or refused row carries a number"),
    ],
)


def _hhi_xor_reason(data) -> pl.LazyFrame:
    return data.lazyframe.select(pl.col("hhi").is_null() == pl.col("refusal_reason").is_not_null())


HHI_SCHEMA = pa.DataFrameSchema(
    {
        "segment": pa.Column(str, pa.Check.isin(list(UNIVERSE))),
        "lens": pa.Column(str, pa.Check.isin(["disclosed_pool", "official_denominator"])),
        "pool": pa.Column(str),
        "period": pa.Column(str),
        "n_members": pa.Column(int, pa.Check.ge(0)),
        "full_membership": pa.Column(bool),
        "members": pa.Column(str),
        "excluded": pa.Column(str),
        "pool_total": pa.Column(float, pa.Check.gt(0.0), nullable=True),
        "unit": pa.Column(str),
        "total_qualifier": pa.Column(str, pa.Check.isin(QUALIFIERS), nullable=True),
        "hhi": pa.Column(float, pa.Check.in_range(0.0, 10_000.0), nullable=True),
        "qualifier": pa.Column(str, pa.Check.isin(QUALIFIERS), nullable=True),
        "basis": pa.Column(str),
        "refusal_reason": pa.Column(str, nullable=True),
    },
    unique=HHI_KEY,
    strict=True,
    coerce=False,
    checks=[pa.Check(_hhi_xor_reason, error="an HHI row carries a value or a refusal reason, never both")],
)


def _row(**kw) -> dict:
    out = {k: None for k in LONG_DTYPES}
    out["stale"] = False
    out.update(kw)
    return out


def _frame(rows: list[dict], dtypes: dict[str, pl.DataType]) -> pl.DataFrame:
    if not rows:
        return pl.DataFrame(schema=dtypes)
    return pl.DataFrame(rows, schema=dtypes)


# --- curated inputs --------------------------------------------------------------------------


@dataclass
class Obs:
    company: str
    metric: str
    period: str          # as written
    cal: str | None      # calendar label, or None when it cannot be aligned
    gran: str
    value: float
    qualifier: str
    unit: str
    kind: str
    chartable: bool
    stale: bool
    reasons: list[str]   # why this observation cannot enter a USD period-total pool; empty = eligible


def _obs(r: dict) -> Obs:
    cal, align = calendar_period(str(r["period"]), str(r["as_of_date"]))
    reasons: list[str] = []
    if r.get("chartable") is not True or r.get("metric_kind") in NEVER_CHARTED_KINDS:
        reasons.append(f"curated row not chartable (tag {r.get('tag')}, {r.get('metric_kind')})")
    if r.get("unit") != USD:
        reasons.append(f"reported in {r.get('unit')}; pools are in USD and share.py does not convert currencies")
    if r.get("metric_kind") == "stated_run_rate":
        reasons.append("annualised run rate; never mixed with period totals")
    if align and r.get("metric_kind") != "stated_run_rate":
        reasons.append(align)
    return Obs(company=r["company"], metric=r["metric"], period=str(r["period"]), cal=cal,
               gran=granularity(str(r["period"])), value=float(r["value"]), qualifier=r["qualifier"],
               unit=str(r.get("unit")), kind=str(r.get("metric_kind")), chartable=r.get("chartable") is True,
               stale=bool(r.get("stale")), reasons=reasons)


@dataclass
class Resolved:
    value: float | None
    qualifier: str | None
    how: str
    stale: bool
    reasons: list[str]


def _quarters(year: int) -> list[str]:
    return [f"{year}-Q{q}" for q in (1, 2, 3, 4)]


def resolve(obs: list[Obs], period: str) -> Resolved:
    """One member's volume for one calendar period (a quarter 'YYYY-Qn' or a year 'FYYYYY')."""
    by_cal: dict[str, Obs] = {o.cal: o for o in obs if o.cal}
    general = sorted({r for o in obs for r in o.reasons
                      if r.startswith("reported in") or r.startswith("annualised")})
    if re.fullmatch(r"\d{4}-Q[1-4]", period):
        o = by_cal.get(period)
        if o is not None:
            if o.reasons:
                return Resolved(None, None, "", o.stale, o.reasons)
            return Resolved(o.value, o.qualifier, f"{o.period} as reported", o.stale, [])
        grans = {x.gran for x in obs}
        why = [f"no quarterly figure for {period}"]
        if obs and "quarter" not in grans:
            why = [f"reports {'half-years' if 'half' in grans else 'annual or run-rate figures'} only"]
        return Resolved(None, None, "", False, general + why)
    year = int(period[2:])
    native = by_cal.get(period)
    if native is not None and not native.reasons:
        return Resolved(native.value, native.qualifier, f"{native.period} as reported", native.stale, [])
    for parts, label in ((_quarters(year), "sum of four calendar quarters"),
                         ([f"H1-{year}", f"H2-{year}"], "H1 + H2")):
        got = [by_cal.get(p) for p in parts]
        if all(g is not None and not g.reasons for g in got):
            vals = [g for g in got if g is not None]
            return Resolved(sum(g.value for g in vals), q_sum(g.qualifier for g in vals),
                            f"{label} ({', '.join(g.period for g in vals)})", any(g.stale for g in vals), [])
    reasons = list(native.reasons) if native is not None else []
    for p in _quarters(year) + [f"H1-{year}", f"H2-{year}"]:
        g = by_cal.get(p)
        if g is not None and g.reasons:
            reasons += g.reasons
    if not reasons:
        reasons = general + [f"no complete calendar {year} (needs FY{year}, four quarters or H1 + H2)"]
    return Resolved(None, None, "", False, sorted(set(reasons)))


def _member_obs(kpi: list[dict], m: Member) -> list[Obs]:
    return [_obs(r) for r in kpi if r["company"] == m.company and r["metric"] == m.metric]


def _candidate_periods(obs_by_member: dict[str, list[Obs]]) -> list[str]:
    out: set[str] = set()
    for obs in obs_by_member.values():
        for o in obs:
            if not o.cal:
                continue
            if o.gran == "quarter":
                out.add(o.cal)
                out.add(f"FY{o.cal[:4]}")
            elif o.gran == "half":
                out.add(f"FY{o.cal[-4:]}")
            elif o.gran == "year":
                out.add(o.cal)
    return sorted(out, key=period_sort_key)


# --- lens 1: disclosed pool ------------------------------------------------------------------


def disclosed_pool(kpi: list[dict], private: list[dict], pools: tuple[Pool, ...] = POOLS
                   ) -> tuple[list[dict], list[dict]]:
    long: list[dict] = []
    hhi: list[dict] = []
    for pool in pools:
        obs_by = {m.label: _member_obs(kpi, m) for m in pool.members}
        for period in _candidate_periods(obs_by):
            got = {m.label: resolve(obs_by[m.label], period) for m in pool.members}
            members = [m for m in pool.members if got[m.label].value is not None]
            if not members:
                continue
            excluded = [m for m in pool.members if got[m.label].value is None]
            total = sum(got[m.label].value for m in members)  # type: ignore[misc]
            total_q = q_sum(got[m.label].qualifier for m in members)  # type: ignore[misc]
            enough = len(members) >= MIN_POOL_MEMBERS
            share_qs = []
            for m in members:
                r = got[m.label]
                rest = [got[o.label] for o in members if o is not m]
                base = dict(segment=pool.segment, lens="disclosed_pool", pool=pool.id, company=m.label,
                            period=period, role="member", source_metric=f"{m.company}: {m.metric}",
                            stale=r.stale)
                if enough:
                    q = q_share(r.qualifier, q_sum(x.qualifier for x in rest))  # type: ignore[arg-type]
                    share_qs.append(q)
                    long.append(_row(**base, value=r.value / total, unit=UNIT_POOL, qualifier=q,  # type: ignore[operator]
                                     basis=f"share of disclosed pool; {r.how}; {pool.basis}"))
                else:
                    long.append(_row(**base, unit=UNIT_POOL, basis=f"{r.how}; {pool.basis}",
                                     refusal_reason=f"only {len(members)} disclosing member for {period}; "
                                                    "a one-company pool is 100% by construction"))
            for m in excluded:
                long.append(_row(segment=pool.segment, lens="disclosed_pool", pool=pool.id, company=m.label,
                                 period=period, unit=UNIT_POOL, role="excluded", basis=pool.basis,
                                 refusal_reason="; ".join(got[m.label].reasons),
                                 source_metric=f"{m.company}: {m.metric}"))
            hhi.append({
                "segment": pool.segment, "lens": "disclosed_pool", "pool": pool.id, "period": period,
                "n_members": len(members), "members": ", ".join(m.label for m in members),
                "excluded": "; ".join(f"{m.label} ({'; '.join(got[m.label].reasons)})" for m in excluded),
                "pool_total": float(total), "unit": USD, "total_qualifier": total_q,
                "hhi": sum((got[m.label].value / total * 100) ** 2 for m in members) if enough else None,  # type: ignore[operator]
                "qualifier": q_hhi(share_qs) if enough else None,
                "basis": f"HHI inside the disclosed pool only (0-10,000); {pool.basis}",
                "refusal_reason": None if enough else
                f"only {len(members)} disclosing member; concentration of a one-company pool is meaningless",
            })
        for company, reason in pool.not_in_pool.items():
            if any(mk.company == company for mk in pool.markers):
                continue
            long.append(_row(segment=pool.segment, lens="disclosed_pool", pool=pool.id, company=company,
                             unit=UNIT_POOL, role="excluded", basis=pool.basis, refusal_reason=reason))
        mine = [h for h in hhi if h["pool"] == pool.id]
        most = max((h["n_members"] for h in mine), default=0)
        for h in mine:
            h["full_membership"] = h["n_members"] == most
        pool_periods = {h["period"] for h in mine}
        for mk in pool.markers:
            for r in private:
                if r["company"] != mk.company or r["metric"] != mk.metric:
                    continue
                if r.get("chartable") is not True or r.get("metric_kind") in NEVER_CHARTED_KINDS:
                    continue  # unconfirmed figures go to the ledger's "reported, unconfirmed" table only
                cal, _ = calendar_period(str(r["period"]), str(r["as_of_date"]))
                period = cal or str(r["period"])
                same = "a pool exists for the same period" if period in pool_periods else "no pool for this period"
                long.append(_row(segment=pool.segment, lens="disclosed_pool", pool=pool.id, company=mk.company,
                                 period=period, value=float(r["value"]), unit=str(r["unit"]),
                                 qualifier=r["qualifier"], role="marker",
                                 basis=f"marker, not a share: {mk.reason}; {r['metric_kind']}; {same}",
                                 source_metric=f"{mk.company}: {mk.metric}", stale=bool(r.get("stale"))))
    for seg, reason in NO_POOL.items():
        long.append(_row(segment=seg, lens="disclosed_pool", pool=f"{seg}_none", unit=UNIT_POOL, role="refused",
                         basis="no pool", refusal_reason=reason))
    return long, hhi


def latest_common_period(hhi: pl.DataFrame, pool: str, quarterly: bool = True) -> str | None:
    """Latest period in which the pool has its full membership (no member missing for a period reason)."""
    h = hhi.filter((pl.col("pool") == pool) & pl.col("full_membership"))
    if quarterly:
        h = h.filter(pl.col("period").str.contains("-Q"))
    periods = h["period"].to_list()
    return max(periods, key=period_sort_key) if periods else None


# --- lens 2: official denominator ------------------------------------------------------------


def _feds(denoms: list[dict]) -> tuple[list[dict], list[dict], list[dict]]:
    """Shares from the FEDS table, the table's own HHI, and a reconciliation against its printed shares."""
    rows = [d for d in denoms if d["series"] == FEDS_SERIES and d.get("chartable") is True]
    total = next((d for d in rows if d["metric"] == FEDS_TOTAL), None)
    if total is None:
        return [], [], []
    long, recon = [], []
    shares: dict[str, tuple[float, str]] = {}
    for key, company in FEDS_COMPANY.items():
        num = next((d for d in rows if d["metric"] == f"us_bnpl_issuance_{key}"), None)
        if num is None:
            long.append(_row(segment="B", lens="official_denominator", pool=FEDS_SERIES, company=company,
                             period=total["period"], unit=UNIT_OFFICIAL, role="excluded", basis=FEDS_BASIS,
                             refusal_reason="no chartable issuance row for this provider in the curated table"))
            continue
        s = float(num["value"]) / float(total["value"])
        q = q_ratio(num["qualifier"], total["qualifier"])
        shares[company] = (s, q)
        long.append(_row(segment="B", lens="official_denominator", pool=FEDS_SERIES, company=company,
                         period=total["period"], value=s, unit=UNIT_OFFICIAL, qualifier=q, role="member",
                         basis=FEDS_BASIS, source_metric=f"{FEDS_SERIES}: us_bnpl_issuance_{key} / {FEDS_TOTAL}",
                         stale=bool(num.get("stale") or total.get("stale"))))
        printed = next((d for d in rows if d["metric"] == f"us_bnpl_issuance_share_{key}"), None)
        if printed is not None:
            tol = FEDS_ROUNDING_PP + FEDS_TABLE_HALF_UNIT / float(total["value"]) * 100
            recon.append({"company": company, "computed_pp": s * 100, "printed_pp": float(printed["value"]),
                          "tolerance_pp": tol})
    hhi = []
    if shares:
        enough = len(shares) >= MIN_POOL_MEMBERS
        covered = sum(v for v, _ in shares.values())
        hhi.append({
            "segment": "B", "lens": "official_denominator", "pool": FEDS_SERIES, "period": total["period"],
            "n_members": len(shares), "full_membership": len(shares) == len(FEDS_COMPANY),
            "members": ", ".join(shares), "excluded": "",
            "pool_total": float(total["value"]), "unit": str(total["unit"]), "total_qualifier": total["qualifier"],
            "hhi": sum((v * 100) ** 2 for v, _ in shares.values()) if enough else None,
            "qualifier": q_hhi(q for _, q in shares.values()) if enough else None,
            "basis": f"HHI over the six providers in the FEDS table ({covered:.1%} of its total); {FEDS_BASIS}",
            "refusal_reason": None if enough else "fewer than two providers",
        })
    return long, hhi, recon


def _company_vs_denominator(kpi: list[dict], denoms: list[dict], pools: tuple[Pool, ...]) -> list[dict]:
    """Pool members against each official total for their layer: a number only when scope, measure and
    period all match; otherwise a refusal row that says which test failed."""
    out = []
    for den in DENOMINATORS:
        drows = [d for d in denoms if d["series"] == den.series and d["metric"] == den.metric
                 and d.get("chartable") is True]
        if not drows:
            continue
        drow = max(drows, key=lambda d: period_sort_key(calendar_period(d["period"], d["as_of_date"])[0]))
        dper, _ = calendar_period(drow["period"], drow["as_of_date"])
        for pool in pools:
            if pool.segment != den.segment:
                continue
            for m in pool.members:
                obs = _member_obs(kpi, m)
                if not obs:
                    continue
                reasons = []
                if m.scope != den.scope:
                    reasons.append(f"scope: volume covers {m.scope}, the denominator is {den.scope}-only")
                if m.measure != den.measure:
                    reasons.append(f"measure: {m.measure} is not {den.measure}")
                r = resolve(obs, dper) if dper else Resolved(None, None, "", False, ["denominator period unaligned"])
                if r.value is None:
                    reasons.append(f"period: no usable {dper} volume ({'; '.join(r.reasons)})")
                base = dict(segment=den.segment, lens="official_denominator", pool=den.series, company=m.label,
                            period=dper, unit=UNIT_OFFICIAL, source_metric=f"{m.company}: {m.metric} / {den.metric}")
                if reasons:
                    out.append(_row(**base, role="refused", basis=den.label, refusal_reason="; ".join(reasons)))
                else:
                    out.append(_row(**base, role="member", value=r.value / float(drow["value"]),  # type: ignore[operator]
                                    qualifier=q_ratio(r.qualifier, drow["qualifier"]),  # type: ignore[arg-type]
                                    basis=f"{den.label}; {r.how}", stale=r.stale or bool(drow.get("stale"))))
    return out


def official_denominator(kpi: list[dict], denoms: list[dict], pools: tuple[Pool, ...] = POOLS
                         ) -> tuple[list[dict], list[dict], list[dict]]:
    long, hhi, recon = _feds(denoms)
    long += _company_vs_denominator(kpi, denoms, pools)
    for seg, reason in NO_DENOMINATOR.items():
        long.append(_row(segment=seg, lens="official_denominator", pool=f"{seg}_none", unit=UNIT_OFFICIAL,
                         role="refused", basis="no official denominator", refusal_reason=reason))
    return long, hhi, recon


# --- lens 3: web coverage --------------------------------------------------------------------


def web_coverage(adoption: pl.DataFrame | None) -> list[dict]:
    """Latest crawl month, every geo x rank x client slice. A technology below webtech's detectability bar
    (latest all-origins mobile count) gets a refusal, not a near-zero bar."""
    if adoption is None or adoption.is_empty():
        return []
    from pipelines.payments.webtech import MIN_DETECTABLE_ORIGINS, TECHNOLOGIES, build_coverage

    cov = build_coverage(adoption)
    notes = {r["technology"]: r for r in cov.iter_rows(named=True)}
    latest = adoption["date"].max()
    out = []
    current = adoption.filter(pl.col("date") == latest).sort(["technology", "geo", "rank", "client"])
    for r in current.iter_rows(named=True):
        if r["technology"] not in WEB_TECH_COMPANY:
            continue
        seg, company = WEB_TECH_COMPANY[r["technology"]]
        geo = "US" if r["geo"] != "ALL" else "all geographies"
        slice_ = f"web: {geo} / {r['rank']} / {r['client']}"
        note = TECHNOLOGIES.get(r["technology"], "")
        basis = ("coverage, not share of payments: origins where HTTP Archive detects the technology over all "
                 f"origins in the slice ({r['origins']:,} of {r['total_origins'] or 0:,})"
                 + (f"; {note}" if note else ""))
        base = dict(segment=seg, lens="web_coverage", pool=slice_, company=company, period=latest.strftime("%Y-%m"),
                    unit=UNIT_ORIGINS, source_metric=f"HTTP Archive: {r['technology']}")
        c = notes.get(r["technology"])
        if c is not None and not c["detectable"]:
            out.append(_row(**base, role="refused", basis=basis,
                            refusal_reason=f"barely detected (latest all-origins mobile count {c['latest_origins']:,}, "
                                           f"below {MIN_DETECTABLE_ORIGINS:,}); {c['note']}"))
        elif r["share"] is None:
            out.append(_row(**base, role="refused", basis=basis,
                            refusal_reason="crawl total for this slice is missing, so no denominator"))
        else:
            out.append(_row(**base, role="measured", value=float(r["share"]), qualifier="=", basis=basis))
    return out


# --- lens 4: developer downloads -------------------------------------------------------------


def _download_shares(monthly: pl.DataFrame, side: str, expected: list[str], slice_: str, basis: str) -> list[dict]:
    m = monthly.filter((pl.col("registry") == "npm") & (pl.col("side") == side))
    if m.is_empty():
        return []
    full = (m.group_by("period").agg(pl.col("series").n_unique().alias("n"))
            .filter(pl.col("n") == len(expected)).sort("period"))
    if full.is_empty():
        return []
    latest = full["period"].max()
    rows = m.filter(pl.col("period") == latest).sort("series")
    total = int(rows["downloads"].sum())
    if total <= 0:
        return []
    out = []
    for r in rows.iter_rows(named=True):
        company = r["company"]
        out.append(_row(segment=SEGMENT_OF.get(company, "A"), lens="developer_downloads", pool=slice_,
                        company=company if side == "client" else f"{company} ({r['series']})",
                        period=latest.strftime("%Y-%m"), value=r["downloads"] / total, unit=UNIT_DOWNLOADS,
                        qualifier="=", role="measured",
                        basis=f"{basis}; {r['downloads']:,} of {total:,} downloads; packages {r['packages']}",
                        source_metric=f"npm: {r['packages']}"))
    return out


def developer_downloads(client_monthly: pl.DataFrame | None, server_monthly: pl.DataFrame | None) -> list[dict]:
    out: list[dict] = []
    if client_monthly is not None:
        out += _download_shares(
            client_monthly, "client", list(NPM_CLIENT_SDKS), "npm client SDKs (registered Q1 set)",
            "share of client-SDK npm downloads among the five registered companies (layers A and D); "
            "downloads include CI and mirrors and are not developers or dollars")
    if server_monthly is not None:
        out += _download_shares(
            server_monthly, "server", list(NPM_SERVER_SDKS), "npm server SDKs (descriptive)",
            "share of server-SDK npm downloads among the three pinned packages; descriptive only, not in Q1")
    return out


# --- Q1 volume interval ----------------------------------------------------------------------

Q1_COMPANIES = list(NPM_CLIENT_SDKS)  # Stripe, Adyen, PayPal, Checkout.com, Airwallex


def q1_volume_share(kpi: list[dict], private: list[dict], year: int, eur_usd: float | None = None) -> dict:
    """Stripe's share of calendar-year volume among the five registered Q1 companies, as an interval.

    Each member is an interval: its qualifier (``bounds``) plus anything missing. PayPal is its calendar-year
    TPV; Adyen is H1 + H2 processed volume converted at ``eur_usd`` (USD per EUR, a calendar-year average) and
    unbounded below without one; Stripe and Checkout.com are their stated calendar-year totals; a member with no
    calendar-year figure (Airwallex states only annualised run rates) is [0, inf). Then
    ``upper = S_hi / (S_hi + sum others_lo)`` and ``lower = S_lo / (S_lo + sum others_hi)``. Q1 grades on the
    upper bound. PayPal TPV includes Venmo and P2P and no curated merchant-only split exists, so PayPal enters as
    ``[0, full TPV]``: its low end is 0, which keeps ``upper`` a true upper bound. The share with PayPal at its
    full TPV (not a bound; Venmo/P2P counted as merchant volume) is returned separately as
    ``upper_if_paypal_full_tpv`` for context, never for grading.
    """
    members: dict[str, tuple[float, float, str]] = {}

    def _private(company: str) -> dict | None:
        for r in private:
            if (r["company"] == company and r.get("chartable") is True and r.get("unit") == USD
                    and r.get("metric_kind") not in NEVER_CHARTED_KINDS and r.get("metric_kind") != "stated_run_rate"
                    and calendar_period(str(r["period"]), str(r["as_of_date"]))[0] == f"FY{year}"
                    and "volume" in str(r["metric"]) and "expected" not in str(r["metric"])):
                return r
        return None

    for company in ("Stripe", "Checkout.com", "Airwallex"):
        r = _private(company)
        if r is None:
            members[company] = (0.0, math.inf, f"no chartable calendar-{year} volume; unbounded")
        else:
            lo, hi = bounds(float(r["value"]), r["qualifier"])
            members[company] = (lo, hi, f"{r['metric']} {r['period']} ({r['qualifier']})")
    pp = resolve(_member_obs(kpi, POOLS[0].members[0]), f"FY{year}")
    paypal_full_lo: float | None = None
    if pp.value is None:
        members["PayPal"] = (0.0, math.inf, "; ".join(pp.reasons))
    else:
        paypal_full_lo, hi = bounds(pp.value, pp.qualifier)  # type: ignore[arg-type]
        # no curated merchant-only split: the merchant volume lies anywhere in [0, full TPV]
        members["PayPal"] = (0.0, hi, f"TPV {pp.how} incl. Venmo/P2P; merchant-only lower bound unknown (0)")
    adyen = [r for r in kpi if r["company"] == "Adyen" and r["metric"] == "processed_volume"
             and r.get("chartable") is True and r["period"] in (f"H1-{year}", f"H2-{year}")]
    if eur_usd and len(adyen) == 2:
        eur = sum(float(r["value"]) for r in adyen)
        lo, hi = bounds(eur * eur_usd, q_sum(r["qualifier"] for r in adyen))
        members["Adyen"] = (lo, hi, f"H1 + H2 {year} in EUR x {eur_usd} USD/EUR")
    else:
        members["Adyen"] = (0.0, math.inf, "EUR volume not converted (no calendar-year EUR/USD rate supplied)"
                            if len(adyen) == 2 else f"no H1 + H2 {year} processed volume")
    s_lo, s_hi, _ = members["Stripe"]
    others_lo = sum(v[0] for k, v in members.items() if k != "Stripe")
    others_hi = sum(v[1] for k, v in members.items() if k != "Stripe")
    upper = None if (s_hi == math.inf or s_hi + others_lo <= 0) else s_hi / (s_hi + others_lo)
    lower = 0.0 if (others_hi == math.inf or s_lo + others_hi <= 0) else s_lo / (s_lo + others_hi)
    full_den = s_hi + others_lo + (paypal_full_lo or 0.0)
    upper_full = (None if (paypal_full_lo is None or s_hi == math.inf or full_den <= 0) else s_hi / full_den)
    return {"year": year, "lower": lower, "upper": upper, "upper_if_paypal_full_tpv": upper_full,
            "members": {k: {"low": v[0], "high": None if v[1] == math.inf else v[1], "basis": v[2]}
                        for k, v in members.items()}}


# --- build, check, write ---------------------------------------------------------------------


@dataclass
class ShareTables:
    long: pl.DataFrame
    hhi: pl.DataFrame
    checks: list[dict]


def _read_optional(path: Path) -> tuple[pl.DataFrame | None, str | None]:
    """(frame, None) when readable, (None, None) when absent, (None, error) when present but unreadable."""
    if not path.exists():
        return None, None
    try:
        return pl.read_parquet(path), None
    except (OSError, pl.exceptions.PolarsError) as e:
        log.warning("could not read %s: %s", path, e)
        return None, f"{path.name}: {type(e).__name__}: {e}"


def _join_err(*errs: str | None) -> str | None:
    errs_ = [e for e in errs if e]
    return "; ".join(errs_) if errs_ else None


def build(kpi: list[dict] | None = None, private: list[dict] | None = None, denoms: list[dict] | None = None,
          *, marts_dir: Path | None = None, adoption: pl.DataFrame | None = None,
          client_monthly: pl.DataFrame | None = None, server_monthly: pl.DataFrame | None = None,
          read_marts: bool = True) -> ShareTables:
    """All four lenses. Curated rows default to reference.rows(); webtech/devstats marts are read from
    ``marts_dir`` when not passed and ``read_marts`` is true (they exist only after a CI run)."""
    if kpi is None:
        kpi = reference.rows("kpi_disclosures_acceptance") + reference.rows("kpi_disclosures_other")
    if private is None:
        private = reference.rows("private_metrics")
    if denoms is None:
        denoms = reference.rows("denominators")
    md = marts_dir or OUT_DIR
    web_err = client_err = server_err = None
    if read_marts:
        if adoption is None:
            adoption, web_err = _read_optional(md / "webtech_adoption.parquet")
        if client_monthly is None:
            client_monthly, client_err = _read_optional(md / "devstats_client_monthly.parquet")
        if server_monthly is None:
            server_monthly, server_err = _read_optional(md / "devstats_server_monthly.parquet")
    dl_err = _join_err(client_err, server_err)

    pool_long, pool_hhi = disclosed_pool(kpi, private)
    off_long, off_hhi, recon = official_denominator(kpi, denoms)
    # the mart-fed lenses fail independently (CLAUDE.md rule 5): a bad mart empties its own lens only
    web_long: list[dict] = []
    if web_err is None:
        try:
            web_long = web_coverage(adoption)
        except Exception as e:  # noqa: BLE001 - isolate any drift in the webtech mart
            log.exception("web-coverage lens failed")
            web_err = f"{type(e).__name__}: {e}"
    dl_long: list[dict] = []
    if dl_err is None:
        try:
            dl_long = developer_downloads(client_monthly, server_monthly)
        except Exception as e:  # noqa: BLE001 - isolate any drift in the devstats marts
            log.exception("developer-downloads lens failed")
            dl_err = f"{type(e).__name__}: {e}"

    long = _frame(pool_long + off_long + web_long + dl_long, LONG_DTYPES)
    hhi = _frame(pool_hhi + off_hhi, HHI_DTYPES)
    long = LONG_SCHEMA.validate(long)
    hhi = HHI_SCHEMA.validate(hhi)
    checks = quality_checks(long, hhi, recon, adoption=adoption, client_monthly=client_monthly,
                            web_error=web_err, downloads_error=dl_err)
    return ShareTables(long=long, hhi=hhi, checks=checks)


def quality_checks(long: pl.DataFrame, hhi: pl.DataFrame, recon: list[dict], *,
                   adoption: pl.DataFrame | None, client_monthly: pl.DataFrame | None,
                   web_error: str | None = None, downloads_error: str | None = None) -> list[dict]:
    out = [uniqueness(long, LONG_KEY, "share rows", name="Share key uniqueness")]
    shares = long.filter((pl.col("role") == "member") & pl.col("value").is_not_null()
                         & pl.col("lens").is_in(["disclosed_pool", "official_denominator"])
                         & (pl.col("unit") == UNIT_POOL))
    sums = shares.group_by(["pool", "period"]).agg(pl.col("value").sum().alias("s"))
    off = sums.filter((pl.col("s") - 1.0).abs() > 1e-9)
    out.append(check("Pool shares sum to one", off.is_empty(),
                     f"{sums.height} pool-periods; {off.height} not summing to 1"))
    bad = [r for r in recon if abs(r["computed_pp"] - r["printed_pp"]) > r["tolerance_pp"] + 1e-9]
    out.append(check("FEDS shares reconcile", bool(recon) and not bad,
                     (f"{len(recon)} recomputed provider shares round to the printed Figure 1b values"
                      if recon and not bad else
                      "no FEDS rows" if not recon else
                      "off by more than the printed rounding: " + ", ".join(f"{r['company']} {r['computed_pp']:.1f} vs "
                                                             f"{r['printed_pp']:.0f}" for r in bad))))
    latest_a = hhi.filter((pl.col("pool") == "A_payment_volume") & pl.col("period").str.contains("-Q"))
    if latest_a.height:
        last = max(latest_a["period"].to_list(), key=period_sort_key)
        row = latest_a.filter(pl.col("period") == last).row(0, named=True)
        out.append(check("Acceptance pool membership", row["n_members"] >= 4,
                         f"{row['n_members']} members in {last}: {row['members']}", warn=row["n_members"] >= 2))
    else:
        out.append(check("Acceptance pool membership", False, "no quarterly acceptance pool"))
    # absent marts are expected locally (warn); a mart that is present but unreadable or drifted is a fail
    if web_error:
        out.append(check("Share input: web coverage", False, f"read/derive failed: {web_error}"))
    else:
        out.append(check("Share input: web coverage", adoption is not None and not adoption.is_empty(),
                         "webtech_adoption.parquet read" if adoption is not None and not adoption.is_empty()
                         else "webtech output absent (it exists only after a CI run); web-coverage lens empty",
                         warn=True))
    if downloads_error:
        out.append(check("Share input: developer downloads", False, f"read/derive failed: {downloads_error}"))
    else:
        out.append(check("Share input: developer downloads",
                         client_monthly is not None and not client_monthly.is_empty(),
                         "devstats_client_monthly.parquet read" if client_monthly is not None
                         and not client_monthly.is_empty()
                         else "devstats output absent (it exists only after a CI run); downloads lens empty",
                         warn=True))
    return out


def write(t: ShareTables, out_dir: Path | None = None) -> list[Path]:
    """Validate, then write both tables (a schema failure raises before any write)."""
    out_dir = out_dir or OUT_DIR
    long = LONG_SCHEMA.validate(t.long)
    hhi = HHI_SCHEMA.validate(t.hhi)
    return [write_parquet(long, out_dir / LONG_FILE), write_parquet(hhi, out_dir / HHI_FILE)]


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--dry-run", action="store_true", help="build and validate, write nothing")
    args = ap.parse_args(argv)
    setup_logging()
    t = build()
    for c in t.checks:
        log.info("[%s] %s: %s", c["status"], c["name"], c["detail"])
    if not args.dry_run:
        for p in write(t):
            log.info("wrote %s", p)
    return 1 if any(c["status"] == "fail" for c in t.checks) else 0


if __name__ == "__main__":
    sys.exit(main())
